# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'proj_DOD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for proj_DOD
    pod 'RxSwift', '6.1.0'
    pod 'RxCocoa', '6.1.0'
    pod 'RxGesture'
    pod 'DLRadioButton', '~> 1.4'

    pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
    pod 'KakaoSDKAuth'  # 사용자 인증
    pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리



  target 'proj_DODTests' do
    inherit! :search_paths
    # Pods for testing



  end

  target 'proj_DODUITests' do
    # Pods for testing
  end

end
